project:
  type: book
  output-dir: docs

book:
  title: "Programming and Data Analysis with R"
  author: "Thiyanga S. Talagala"
  date: ""
  chapters:
    - index.qmd
    - intro.qmd
    - chap2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

