project:
  type: book
  output-dir: docs

book:
  title: "Programming and Data Analysis with R"
  author: "Thiyanga S. Talagala"
  google-analytics: "G-P3WZLH486T"
  date: ""
  page-footer: "Copyright 2025, Thiyanga S. Talagala"
  chapters:
    - index.qmd
    - intro.qmd
    - chap2.qmd
    - chap3.qmd
    - chap4.qmd
    - chap5.qmd
    - chap6.qmd
    - chap7.qmd
    - chap8.qmd
    - chap9.qmd
    - chap10.qmd
    - chap11.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib


format:
  html:
    theme: cosmo

editor: visual
